{
 "title": "Dashboard práctica AMC",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"fast-api\",phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Número de accesos al servidor en la última hora",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(server_requests_total{namespace=\"fast-api\"}) - sum(min_over_time(server_requests_total{namespace=\"fast-api\"} [1h]))"
    }
   ]
  },
  {
   "title": "Número de llamadas a '/' en la última hora",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(main_requests_total{namespace=\"fast-api\"}) - sum(min_over_time(main_requests_total{namespace=\"fast-api\"} [1h]))"
    }
   ]
  },
  {
   "title": "Número de reinicios del pod fast-api-webapp",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"fast-api-webapp\"}"
    }
   ]
  },
  {
   "title": "Número de accesos a '/bye' en la última hora",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bye_requests_total{namespace=\"fast-api\"}) - sum(min_over_time(bye_requests_total{namespace=\"fast-api\"} [1h]))"
    }
   ]
  },
  {
   "title": "Número de accesos a '/health' en la última hora",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_requests_total{namespace=\"fast-api\"}) - sum(min_over_time(healthcheck_requests_total{namespace=\"fast-api\"} [1h]))"
    }
   ]
  },
  {
   "title": "CPU: Consumo Vs Limite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"fast-api\", resource=\"cpu\",pod=~\"my-app-fast-api-webapp.*\"}",
     "legendFormat": "CPU reservada"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"my-app-fast-api.*\", namespace=\"fast-api\"}[1m]))",
     "legendFormat": "CPU en uso"
    }
   ]
  },
  {
   "title": "RAM= Limite vs Reservada",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Memoria usada"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Memoria reservada"
    }
   ]
  }
 ]
}